name: 'NodeDockerApp'
on: [push]
jobs:
 jfrog-ci-integration:
   runs-on: ubuntu-latest
   env:
     BUILD_NAME: 'NodeDockerApp'
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - uses: jfrog/setup-jfrog-cli@v4
       with:
        version: latest
       env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_USER: ${{secrets.JF_USER}}
        JF_ACCESS_TOKEN: ${{secrets.JF_ACCESS_TOKEN}}
     - run: jf --version
     - name: Build and publish
       run: |
         # Configure the project
         jf npmc --repo-resolve alpha-npm-virtual
         # Build the project using JFrog CLI
         jf npm install --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
         jf npm publish --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
     - name: Failure check
       run: |
         echo "JFROG_BUILD_STATUS=FAIL" >> $GITHUB_ENV
       if: failure()
     - name: Publish build NPM build-info
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce ${{env.BUILD_NAME}} ${{github.run_number}}
         # Collect and store VCS details in the build-info
         jf rt bag ${{env.BUILD_NAME}} ${{github.run_number}}
         # Publish the build-info to Artifactory
         jf rt bp ${{env.BUILD_NAME}} ${{github.run_number}}
         # Scan the published build-info with Xray
         # jf rt bs
       if: always()
     - name: Publish build NPM build-info
       run: |
        docker login --url=${{env.JF_URL}} --user${{env.JF_USER}} --password=${{env.JF_PASSWORD}}
        docker build -t node-web-app .
        docker images
        docker tag node-web-app soleng.jfrog.io/alpha-docker-virtual/node-web-app:${{github.run_number}}
        docker push soleng.jfrog.io/alpha-docker-virtual/node-web-app:${{github.run_number}}
